Add checks

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,20 +12,34 @@ jobs:
     - name: Release
       run: |
         versions=$(curl -sSL https://getcomposer.org/versions)
-        for v in stable preview snapshot; do
-          curl -o composer-$v.phar -sSL https://getcomposer.org$(echo $versions | jq -r ".\"$v\"[].path")
-        done
-        for v in 1 2; do
-          curl -o composer-v$v.phar -sSL https://getcomposer.org$(echo $versions | jq -r ".\"$v\"[].path")
-        done
-        set -x
-        assets=()
-        for asset in ./*.phar; do
-          assets+=("-a" "$asset")
-        done
-        time=$(date '+%Y-%m-%d %H:%M:%S')
-        git push -f origin :1.0.0 || true
-        hub release delete "1.0.0" || true
-        hub release create "${assets[@]}" -m "$time" "1.0.0"
+        release_versions=$(curl -sSL https://github.com/shivammathur/composer-cache/releases/latest/download/versions)
+        if [ "$versions" = "$release_versions" ]; then
+          echo "No new releases"
+        else
+          for v in stable preview snapshot 1 2; do
+            curl -o composer-$v.phar -sSL https://getcomposer.org$(echo $versions | jq -r ".\"$v\"[].path")
+            php -r "try {\$p=new Phar('composer-$v.phar', 0);exit(0);} catch(Exception \$e) {exit(1);}"
+            if [ $? -eq 1 ]; then
+              echo "Could not download composer $v"
+              exit 1;
+            else
+              sudo cp ./composer-$v.phar /usr/local/bin/composer
+              sudo chmod a+x /usr/local/bin/composer
+              composer -V
+            fi
+          done
+          curl -o versions -sSL https://getcomposer.org/versions
+          set -x
+          assets=()
+          for asset in ./*.phar; do
+            assets+=("-a" "$asset")
+          done
+          assets+=("-a" "./versions")
+          echo "${assets[@]}"
+          time=$(date '+%Y-%m-%d %H:%M:%S')
+          git push -f origin :1.0.0 || true
+          hub release delete "1.0.0" || true
+          hub release create "${assets[@]}" -m "$time" "1.0.0"
+        fi
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
